# -*-makefile-*-
#
# by exa aka Eray Ozkural 2001
# see COPYING file that comes with this distribution

# Programs used

include build/Makefile.utilities

define check-dir
@if [ ! -d $(workingdir) ]; then\
  echo Creating directory $(workingdir);\
  mkdir $(workingdir);\
 fi
@if [ ! -d $(bin) ]; then\
  echo Creating directory $(bin);\
  mkdir $(bin);\
 fi
@if [ ! -d $(lib) ]; then\
  echo Creating directory $(lib);\
  mkdir $(lib);\
 fi
endef

define \n


endef
